# Generated by Django 6.0 on 2025-12-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerotp',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
