# Generated by Django 6.0 on 2026-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_registerotp_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerotp',
            name='age',
        ),
        migrations.RemoveField(
            model_name='registerotp',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='registerotp',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registerotp',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='registerotp',
            name='skin_type',
        ),
        migrations.AddField(
            model_name='registerotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
